# Config file for automatic testing at travis-ci.org
language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

install:
  - pip install -r dev-requirements.txt
  - pip install .

script: py.test
